### ISSUE TITLE
Add link to PIFSC UxS project's existing transition plan?

### ISSUE THREAD

**Issue by sfregosi** [NMFS-PAM-Glider/PAM-UxS#2]
Worth adding, or will cause confusion? 

https://drive.google.com/drive/u/0/folders/1_yK9UhQrQgfKACIGHFkGoEk8G1CukEcR

**Comment by shannonrankin** [comment]
Would it be ok if I added this document as a pdf stored within the repository here? I typically create a 'supplemental' folder, and put supplemental documents there. If that is acceptable, happy to do that.  :)

**Comment by sfregosi** [comment]
I think so. Want to double check with @eoleson and will report back.

**Comment by eoleson** [comment]
OK with me.  Probably just the final signed version, not the various Word iterations.

**Comment by shannonrankin** [comment]
Final pdf stored in PAM-UxS/supplemental folder (will push later today)
